# Generated by Django 2.2.8 on 2020-06-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200621_2315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_name',
            field=models.CharField(choices=[('S', '3D Materials'), ('SW', 'Patterns'), ('CV', "CV'd Models")], max_length=2),
        ),
    ]
