# Generated by Django 2.2.8 on 2020-06-22 18:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200622_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_name',
            field=models.CharField(choices=[('S', '3D Materials'), ('SW', 'Patterns'), ('CV', 'CVd Models')], max_length=2),
        ),
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', '3D Materials'), ('SW', 'Patterns'), ('CV', 'CVd Models')], default=django.utils.timezone.now, max_length=2),
            preserve_default=False,
        ),
    ]
